



import 'dart:async';
import 'package:floor/floor.dart';
import 'package:prayers_verses/data/local/first_option_converter.dart';
import 'package:prayers_verses/data/local/my_section_dao.dart';
import 'package:prayers_verses/data/my_section.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

part 'my_section_database.g.dart'; // This file is generated by floor. Run 'flutter pub run build_runner build' to generate.

@Database(version: 1, entities: [MySection])
@TypeConverters([FilterOptionConverter])
abstract class MySectionDatabase extends FloorDatabase {
  
  MySectionDao get mySectionDao;
  
  
}